export enum ActionTypes {
  FETCH_EXPENSES = "FETCH_EXPENSES",
  FETCH_EXPENSES_REQUEST = "FETCH_EXPENSES_REQUEST",
  FETCH_EXPENSES_SUCCESS = "FETCH_EXPENSES_SUCCESS",
  FETCH_EXPENSE_SUCCESS = "FETCH_EXPENSE_SUCCESS",
  SET_PAGE_LIMIT = "SET_PAGE_LIMIT",
  SET_CURRENT_PAGE = "SET_CURRENT_PAGE"
}